services:
  - type: web
    name: libraryy
    env: python
    buildCommand: ./build.sh
    startCommand: python -m gunicorn --chdir libra libra.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: False
      - key: USE_POSTGRES
        value: True
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: True
      - key: DEFAULT_FROM_EMAIL
        sync: false
